apiVersion: apps/v1
kind: Deployment
metadata:
  name: origin-frontend
  namespace: origin-production
  labels:
    app: origin-frontend
    component: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: origin-frontend
  template:
    metadata:
      labels:
        app: origin-frontend
        component: frontend
    spec:
      serviceAccountName: origin-frontend
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: frontend
        image: origin-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: origin-frontend-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: origin-frontend-config
              key: PORT
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            secretKeyRef:
              name: origin-frontend-secrets
              key: NEXT_PUBLIC_API_URL
        - name: NEXT_PUBLIC_FRONTEND_URL
          valueFrom:
            secretKeyRef:
              name: origin-frontend-secrets
              key: NEXT_PUBLIC_FRONTEND_URL
        - name: NEXT_PUBLIC_CDN_URL
          valueFrom:
            secretKeyRef:
              name: origin-frontend-secrets
              key: NEXT_PUBLIC_CDN_URL
        - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: origin-frontend-secrets
              key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        - name: NEXT_PUBLIC_ENABLE_ANALYTICS
          valueFrom:
            configMapKeyRef:
              name: origin-frontend-config
              key: NEXT_PUBLIC_ENABLE_ANALYTICS
        - name: NEXT_PUBLIC_CDN_URL
          valueFrom:
            configMapKeyRef:
              name: origin-frontend-config
              key: NEXT_PUBLIC_CDN_URL
        - name: NEXT_PUBLIC_THEME
          valueFrom:
            configMapKeyRef:
              name: origin-frontend-config
              key: NEXT_PUBLIC_THEME
        - name: NEXT_PUBLIC_CACHE_DURATION
          valueFrom:
            configMapKeyRef:
              name: origin-frontend-config
              key: NEXT_PUBLIC_CACHE_DURATION
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "kubernetes.io/arch"
        operator: "Equal"
        value: "amd64"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - origin-frontend
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: origin-frontend
  namespace: origin-production
  labels:
    app: origin-frontend
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: origin-frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: origin-frontend
  namespace: origin-production
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: origin-frontend-hpa
  namespace: origin-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: origin-frontend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: origin-frontend-pdb
  namespace: origin-production
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: origin-frontend
