# fly.toml app configuration file generated for origin-backend on 2025-10-27T12:29:16-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'origin-backend'
primary_region = 'sjc'

[experimental]
  cmd = ['node', 'dist/main.js']

# Use Dockerfile for custom build
[build]
  dockerfile = "Dockerfile"

[deploy]

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[[mounts]]
  source = 'origin_uploads'
  destination = '/app/uploads'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
