# fly.toml app configuration file generated for origin-backend-misty-shape-4040 on 2025-10-27T12:52:50-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
# Note: This is the Fly.io backup deployment
# Primary deployment runs on: https://originvideo.duckdns.org (162.195.168.34:8080)
#

app = 'origin-backend-misty-shape-4040'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
